// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'firebase_options.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
 
//  Example:
//  ```dart
  // ...

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8HR_Avm-AicmJtsNQK8kq8kel6mkjMsQ',
    appId: '1:227042859645:web:9ce9d4f23c42e2b02eaf14',
    messagingSenderId: '227042859645',
    projectId: 'tracklaw-5714e',
    authDomain: 'tracklaw-5714e.firebaseapp.com',
    storageBucket: 'tracklaw-5714e.firebasestorage.app',
    measurementId: 'G-CS96ERH86D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAXTq4VPTt_2NZZUu2b8_C0E-1XTRvKbM',
    appId: '1:227042859645:android:25e1b8768ca668812eaf14',
    messagingSenderId: '227042859645',
    projectId: 'tracklaw-5714e',
    storageBucket: 'tracklaw-5714e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8NYAU9D5KrB9_emL4SJ7gtMc-Ya1XYVs',
    appId: '1:227042859645:ios:82709524575f3c342eaf14',
    messagingSenderId: '227042859645',
    projectId: 'tracklaw-5714e',
    storageBucket: 'tracklaw-5714e.firebasestorage.app',
    iosBundleId: 'com.example.tracklaw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8NYAU9D5KrB9_emL4SJ7gtMc-Ya1XYVs',
    appId: '1:227042859645:ios:82709524575f3c342eaf14',
    messagingSenderId: '227042859645',
    projectId: 'tracklaw-5714e',
    storageBucket: 'tracklaw-5714e.firebasestorage.app',
    iosBundleId: 'com.example.tracklaw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8HR_Avm-AicmJtsNQK8kq8kel6mkjMsQ',
    appId: '1:227042859645:web:5cb84d9ffef3f57f2eaf14',
    messagingSenderId: '227042859645',
    projectId: 'tracklaw-5714e',
    authDomain: 'tracklaw-5714e.firebaseapp.com',
    storageBucket: 'tracklaw-5714e.firebasestorage.app',
    measurementId: 'G-9WDRM6VMSZ',
  );
}
